package model;

import javafx.collections.FXCollections;
import javafx.collections.ObservableList;

/**
 * Class is a model for a row in the table generated by the Customers by Country report. Data members map to columns in the table. Includes data member getter and setter methods.<br><br>
 * @see reporting.CustomersByCountryReport
 */
public class CountryReportItem {
    private String countryName;
    private int countryId;
    private int numCustomers = 0;
    private int numDivisions = 0;
    private ObservableList<Integer> divisionIdList = FXCollections.observableArrayList();

    /**
     * Class constructor. Sets the country ID and country name for the row.<br><br>
     * @param countryId the Country ID number
     * @param countryName the Country's name
     */
    public CountryReportItem(int countryId, String countryName) {
        this.countryId = countryId;
        this.countryName = countryName;
    }

    /**
     * Gets the number of customers.<br><br>
     * @return the number of customers for the country
     */
    public int getNumCustomers() {
        return numCustomers;
    }

    /**
     * Adds to the total number of customers for the Country. <br><br>
     * @param customers the integer number of customers to add to the CountryReportItem
     */
    public void addNumCustomers(int customers) {
        this.numCustomers = (this.numCustomers + customers);
    }

    /**
     * Gets the Country's name.<br><br>
     * @return the Country's name
     */
    public String getCountryName() {
        return countryName;
    }

    /**
     * Sets the Country's name.<br><br>
     * @param countryName the Country's name
     */
    public void setCountryName(String countryName) {
        this.countryName = countryName;
    }

    /**
     * Gets the Country's ID number<br><br>
     * @return the Country's ID number
     */
    public int getCountryId() {
        return countryId;
    }

    /**
     * Sets the Country's ID number<br><br>
     * @param countryId the Country's ID number
     */
    public void setCountryId(int countryId) {
        this.countryId = countryId;
    }

    /**
     * Gets the total number of divisions for the CountryReportItem<br><br>
     * @return the number of associated divisions
     */
    public int getNumDivisions() {
        return numDivisions;
    }

    /**
     * Increments the total number of divisions associated with the Country by 1.
     */
    public void incrementNumDivisions() {
        this.numDivisions += 1;
    }

    /**
     * Gets the list of division IDs associated with the CountryReportItem<br><br>
     * @return ObservableList of division IDs
     * @see javafx.collections.ObservableList
     */
    public ObservableList<Integer> getDivisionIdList() {
        return divisionIdList;
    }

    /**
     * Adds a division ID to the associated list of division IDs<br><br>
     * @param divisionId the division ID number to add to the list
     */
    public void addToDivisionIdList(int divisionId) {
        this.divisionIdList.add(divisionId);
    }
}
